#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

# boje za terminal
RED="\033[0;31m"
GREEN="\033[0;32m"
YELLOW="\033[1;33m"
NC="\033[0m" # no color

CHANGED_FILES=$(git diff --cached --name-only)

run_tests() {
  FOLDER=$1
  echo -e "${YELLOW}🧪 Running ${FOLDER} tests...${NC}"
  cd $FOLDER
  npm test
  RESULT=$?
  cd ..
  if [ $RESULT -ne 0 ]; then
    echo -e "${RED}❌ ${FOLDER} tests failed! Push blocked.${NC}"
    exit 1
  else
    echo -e "${GREEN}✅ ${FOLDER} tests passed!${NC}"
  fi
}

# client
if echo "$CHANGED_FILES" | grep -q "^client/"; then
  run_tests "client"
fi

# server
if echo "$CHANGED_FILES" | grep -q "^server/"; then
  run_tests "server"
fi
