#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

echo "--- HUSKY PRE-PUSH SKRIPTA SE POKRENULA! ---"
echo "--- AKO VIDITE OVU PORUKU, HOOK RADI. ---"
echo "--- PUSH ĆE SADA BITI NAMJERNO PREKINUT. ---"

# Namjerno prekidamo push da potvrdimo da se skripta izvršava
exit 1